### ISSUE TITLE
Diagrama do projeto 

### ISSUE THREAD

**Issue by sergiohdljr** [rocketseat-education/nlw-expert-nodejs#1]
Não sei se foi disponibilizado em algum outro lugar, mas não está no notion, acho que seria super interessante ter aquele diagrama que foi feito na primeira aula p entendimento do app que está sendo desenvolvido.

**Comment by matheusgmello** [comment]
Aqui está ele
![Diagrama](https://github.com/rocketseat-education/nlw-expert-nodejs/assets/109988623/e838b246-35d4-4dc6-b06e-9f161c5a8ab1)

**Comment by sergiohdljr** [comment]
> Aqui está ele ![Diagrama](https://private-user-images.githubusercontent.com/109988623/303354680-e838b246-35d4-4dc6-b06e-9f161c5a8ab1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MDY0NjgsIm5iZiI6MTcwNzQwNjE2OCwicGF0aCI6Ii8xMDk5ODg2MjMvMzAzMzU0NjgwLWU4MzhiMjQ2LTM1ZDQtNGRjNi1iMDZlLTlmMTYxYzVhOGFiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQxNTI5MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDdhZDQ3NzA0ZTg2NWY1OGRiNGJkMzlmN2YxMjc3ZjAwZDI3MWU0NTUxNWRiYWNjOGIxYjliNDBmYjIzZDk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5LSqcjxpl5hNfK6xU4Fje8yRRoxTbyXgmKaRZk_1YUs)

Muito obrigado, matheus!
