### ISSUE TITLE
Erro ao rodar npx prisma migrate dev

### ISSUE THREAD

**Issue by wagnerfillio** [rocketseat-education/nlw-expert-nodejs#3]
Olá, eu rodei os seguintes comandos:

pnpm install
docker compose up -d
pnpm run dev

E depois npx prisma migrate dev.

No arquivo env não fiz nenhuma alteração, mas quando rodei  npx prisma migrate dev, retornou um erro:

Error: P1001: Can't reach database server at `localhost`:`5432`

Please make sure your database server is running at `localhost`:`5432`.

**Comment by saulotarsobc** [comment]
Copiou o .env.example para .env ?

**Comment by wagnerfillio** [comment]
Copiei sim, e não modifiquei nenhuma linha!
Eu tenho o PostgreSql instalado na maquina, juntamente com o pgAdmin e não sei se faz diferença.
Meu OS é Windows 64b

**Comment by wagnerfillio** [comment]
Resolvido, bastou que eu desinstalasse o postgres do windows.
